### ISSUE TITLE
In a node containing multiple matches of the search string or regex, only the first occurrence is replaced

### ISSUE THREAD

**Issue by lpsinger** [syntax-tree/mdast-util-find-and-replace#5]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-find-and-replace@3.0.0

### Link to runnable example

https://github.com/syntax-tree/mdast-util-find-and-replace/pull/4

### Steps to reproduce

See new unit test in PR above. The search string is the regular expression `/(emph|sis)/` and the replacement text is `'foo'`. So the text node with the content `'emphasis'` should be replaced with three new text nodes, with the contents `'foo'`, `'a'`, and `'foo'`, respectively.

### Expected behavior

The test should pass.

### Actual behavior

The test fails because only the first match is replaced, resulting in only two nodes with the contents `'foo'` and `'asis'`, respectively.

### Affected runtime and version

node@18.17.1

### Affected package manager and version

npm@10.1.0

### Affected OS and version

macOS Ventura 13.5.2

**Comment by lpsinger** [comment]
Oh... right, I didn't set the global `/.../g` flag.

**Comment by wooorm** [comment]
Ah, glad you quickly found it!
