### ISSUE TITLE
Type of `tree` should be `Node`?

### ISSUE THREAD

**Issue by agoose77** [syntax-tree/mdast-util-find-and-replace#6]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

Passing in a `Node` type to `findAndReplace` causes `tsc` to complain. Yet, it appears from the call to `visitParents` that `tree` should really be `Node`, not `Nodes`.

### Expected behavior

The compilation should succeed

### Actual behavior

The compiler complains

### Affected runtime and version

node@22.6.0, typescript@5.6.3

**Comment by wooorm** [comment]
Nope! Node is abstract. You should not use it. Use concrete types

**Comment by agoose77** [comment]
@wooorm thanks!
